import { Property } from "./types";

export const BOARD_PROPERTIES: Property[] = [
  {
    id: 0,
    name: "GO",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 1,
    name: "Old Kent Road",
    price: 60,
    rent: 2,
    color: "brown",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 2,
    name: "Community Chest",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 3,
    name: "Whitechapel Road",
    price: 60,
    rent: 4,
    color: "brown",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 4,
    name: "Income Tax",
    price: 200,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 5,
    name: "Kings Cross Station",
    price: 200,
    rent: 25,
    color: "station",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 6,
    name: "The Angel Islington",
    price: 100,
    rent: 6,
    color: "light-blue",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 7,
    name: "Chance",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 8,
    name: "Euston Road",
    price: 100,
    rent: 6,
    color: "light-blue",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 9,
    name: "Pentonville Road",
    price: 120,
    rent: 8,
    color: "light-blue",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 10,
    name: "Jail",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 11,
    name: "Pall Mall",
    price: 140,
    rent: 10,
    color: "pink",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 12,
    name: "Electric Company",
    price: 150,
    rent: 4,
    color: "utility",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 13,
    name: "Whitehall",
    price: 140,
    rent: 10,
    color: "pink",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 14,
    name: "Northumberland Avenue",
    price: 160,
    rent: 12,
    color: "pink",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 15,
    name: "Marylebone Station",
    price: 200,
    rent: 25,
    color: "station",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 16,
    name: "Bow Street",
    price: 180,
    rent: 14,
    color: "orange",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 17,
    name: "Community Chest",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 18,
    name: "Marlborough Street",
    price: 180,
    rent: 14,
    color: "orange",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 19,
    name: "Vine Street",
    price: 200,
    rent: 16,
    color: "orange",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 20,
    name: "Free Parking",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 21,
    name: "Strand",
    price: 220,
    rent: 18,
    color: "red",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 22,
    name: "Chance",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 23,
    name: "Fleet Street",
    price: 220,
    rent: 18,
    color: "red",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 24,
    name: "Trafalgar Square",
    price: 240,
    rent: 20,
    color: "red",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 25,
    name: "Fenchurch St. Station",
    price: 200,
    rent: 25,
    color: "station",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 26,
    name: "Leicester Square",
    price: 260,
    rent: 22,
    color: "yellow",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 27,
    name: "Coventry Street",
    price: 260,
    rent: 22,
    color: "yellow",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 28,
    name: "Water Works",
    price: 150,
    rent: 4,
    color: "utility",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 29,
    name: "Piccadilly",
    price: 280,
    rent: 24,
    color: "yellow",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 30,
    name: "Go To Jail",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 31,
    name: "Regent Street",
    price: 300,
    rent: 26,
    color: "green",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 32,
    name: "Oxford Street",
    price: 300,
    rent: 26,
    color: "green",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 33,
    name: "Community Chest",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 34,
    name: "Bond Street",
    price: 320,
    rent: 28,
    color: "green",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 35,
    name: "Liverpool St. Station",
    price: 200,
    rent: 25,
    color: "station",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 36,
    name: "Chance",
    price: 0,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 37,
    name: "Park Lane",
    price: 350,
    rent: 35,
    color: "dark-blue",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 38,
    name: "Luxury Tax",
    price: 100,
    rent: 0,
    color: "special",
    owner: null,
    houses: 0,
    mortgage: false,
  },
  {
    id: 39,
    name: "Mayfair",
    price: 400,
    rent: 50,
    color: "dark-blue",
    owner: null,
    houses: 0,
    mortgage: false,
  },
];

export const TOKENS = ["🚂", "🚗", "👞", "🐕", "🎩", "🛳️"];
